#!/bin/bash

NAME="cp_smrmobile_launcher"

DEFAULT_MI_BLOCK="mi"
DEFAULT_MI_TASK="mi_bhbf"

DEFAULT_FEEDBACK_EXECUTABLE="mi_mobile_python"
DEFAULT_IP_LOOP="127.0.0.1"

usage(){
	printf "\n[$NAME] - Usage: $NAME -x XMLPATH -c|-d [OPTION]...\n\n"
	printf "	-x 		path of the xml file\n"
	printf "	-c 		continous mobile control\n"
	printf "	-d 		discrete mobile control\n"
	printf "	-i 		integrator type [ema, dynamic, vema]\n"
	printf "	-b 		experiment block 	[Default: 'mi']\n"
	printf "	-t 		experiment taskset 	[Default: 'mi_bhbf']\n"
	printf "	-e 		Feedback executable [Default: 'mi_online_python']\n"
	printf "	-a 		Loop ip [Default: '127.0.0.1']\n"
}

miblock=$DEFAULT_MI_BLOCK
mitask=$DEFAULT_MI_TASK
feedback=$DEFAULT_FEEDBACK_EXECUTABLE
iploop=$DEFAULT_IP_LOOP
icomponent="integrator"
iname="type"
ccomponent="control"
cname="type"
ctype=""

xflag=false
iflag=false
cflag=false

# Getting optional arguments
while getopts ":t:b:x:i:e:a:dc" opt; do
	case $opt in
		t)
			mitask=$OPTARG

			;;
		b)
			miblock=$OPTARG
			;;
		x)
			bcixml=$OPTARG
			xflag=true;
			;;
		i)
			itype=$OPTARG
			iflag=true;
			;;
		e)
			feedback=$OPTARG
			;;
		a)
			iploop=$OPTARG
			;;
		c)
			ctype="continuous"
			cflag=true
			;;
		d)
			ctype="discrete"
			cflag=true
			;;
		\?)
			echo "[$NAME] - Invalid option: -$OPTARG" >&2
			usage;
			exit 1
			;;
		:)
			echo "[$NAME] - Option -$OPTARG requires an argument.">&2
			usage;
			exit 1
			;;
	esac
done

if ! $xflag 
then
	echo "[$NAME] - XML filepath must be provided (-x XMLPATH)" >&2
	usage;
    exit 1
fi

if ! $iflag 
then
	echo "[$NAME] - integrator type must be provided (-i {ema, dynamic, vema})" >&2
	usage;
    exit 1
fi

if ! $cflag
then
	echo "[$NAME] - control type must be provided (-c|-d)" >&2
	usage;
    exit 1
fi


echo "[$NAME] - BCI xml:  	 $bcixml"
echo "[$NAME] - MI block: 	 $miblock"
echo "[$NAME] - MI task:  	 $mitask"
echo "[$NAME] - Integrator:  $itype"
echo "[$NAME] - Feedback:  	 $feedback"
echo "[$NAME] - Control:  	 $ctype"
echo "[$NAME] - Loop ip:  	 $iploop"


# Upload all parameters to nameserver and start BCI processing
echo "[$NAME] - Uploading XML parameters to nameserver"
cl_init -x $bcixml -lN -B $miblock -T $mitask

# Upload integrator type parameter
echo "[$NAME] - Uploading integrator parameters to nameserver"
cl_rpc storeconfig $icomponent $iname $itype

# Upload control type parameter
echo "[$NAME] - Uploading control parameters to nameserver"
cl_rpc storeconfig $ccomponent $cname $ctype

# Get ic pipe for the device
echo "[$NAME] - Get ic pipe for device"
device_ic=$(ccfg_getstring -x $bcixml -p device/ndf/ic)
echo "[$NAME] - Device connects at $device_ic"

echo "[$NAME] - Starting the ROS slaves with TiC/TiD nodes"
#gnome-terminal --tab -e "bash -c '. $ROS_WORKSPACE_CURRENT/devel/setup.bash && . $ROS_WORKSPACE_CURRENT/setup_network.bash bci && rosparam set /tic_pipes2ros ['$device_ic'] && sleep 1 && rosrun cnbiros_bci rostic'" \
#			   --tab -e "bash -c '. $ROS_WORKSPACE_CURRENT/devel/setup.bash && . $ROS_WORKSPACE_CURRENT/setup_network.bash bci && rosparam set /tid_pipes \"['/bus', '/dev']\" && sleep 1 && rosrun cnbiros_bci rostid'"
BAGNAME=$(ccfg_cli -x $bcixml -N -B $miblock -T $mitask -a)".$itype.bag"
gnome-terminal --tab -e "bash -c '. $ROS_WORKSPACE_CURRENT/devel/setup.bash && roslaunch cnbiros_robotino_bci ros_robotino_telepresence.launch set_tic_pipes2ros:=['$device_ic'] set_bag_name:=$BAGNAME '"

echo "[$NAME] - Opening GDF and log files"
# Open GDF and log files
GDFBASENAME=$(ccfg_cli -x $bcixml -N -B $miblock -T $mitask -a)".$itype.gdf"
LOGBASENAME=$(ccfg_cli -x $bcixml -N -B $miblock -T $mitask -o)
cl_rpc openxdf $GDFBASENAME $LOGBASENAME "smrinc"

echo "[$NAME] - Starting BCI process"
BCIPID=$(cl_init -x $bcixml -scN -B $miblock -T $mitask)

sleep 2

echo "[$NAME] - Launching the GUI"
smrinc_gui_parameters -x $bcixml &

# Launch feedback mi_control
echo "[$NAME] - Launching $feedback feedback"
if [ "$feedback" == "mi_control" ]; then
	#$(gnome-terminal -e $feedback) 
	$feedback
elif [ "$feedback" == "mi_online_python" ]; then
	#$(gnome-terminal -e "$feedback -x $bcixml -t $mitask -b $miblock")
	#feedback=python2
	$feedback -x $bcixml -t $mitask -b $miblock
elif [ "$feedback" == "mi_mobile_python" ]; then
	#$(gnome-terminal -e "$feedback -x $bcixml -t $mitask -b $miblock")
	#feedback=python2
	$feedback -x $bcixml -t $mitask -b $miblock -a $iploop
else
	echo "[$NAME] - Uknown feedback executable provided ($feedback), shutting down"
fi

# Close the GDF file
echo "[$NAME] - Closing GDF file"
cl_rpc closexdf
sleep 1

# Terminate MATLAB prcesses
echo "[$NAME] - Terminating BCI process"
cl_rpc terminate $BCIPID
sleep 1

# Unload configuration from nameserver
echo "[$NAME] - Unload configuration from nameserver"
cl_rpc eraseconfig $icomponent $iname
cl_rpc eraseconfig $ccomponent $cname
sleep 1

# Close ROS local node
#echo "[$NAME] - Close ROS local nodes"
#killall -15 rostic
#killall -15 rostid

# Close python gui
echo "[$NAME] - Close python GUI"
killall -15 python

