#!/bin/bash

GTKDIALOG=gtkdialog
EXECBASH="exec $SHELL -c"
SAVEDIR='/tmp/cnbitk-'$USER'/'
export SAVEDIR

FILEPATH=$SAVEDIR$(date +"%Y%m%d").dynamic_parameters.txt
export FILEPATH

WIN_TITLE="CNBI Mobile"
WIN_W=230
export WIN_W
export WIN_TITLE

LOGOPATH="$HOME/.cnbitk/cnbimobile/gui/cnbi_logo.png"
export LOGOPATH

let "IMG_W = $WIN_W - 40"
export IMG_W

printf "Retrieving integration type from nameserver: "
itype=$(cl_rpc retrieveconfig integrator type)
echo "Type: "$itype

export useralpha
export userrho
export usergamma
export userphi

funcSpinEntry() {
# $1 - Variable name; $2 - Range Min; $3 - Range Max; $4 - Range Step; $5 -Default value; $6 - Title
	echo '
		<text>
			<label>'$6'</label>
		</text>
		<spinbutton digits="2" range-min="'$2'"
		range-max="'$3'" range-step="'$4'"
		range-value="'$5'"
		tooltip-text="'$6' value">
		<sensitive>true</sensitive>
		<variable>'$1'</variable>
		<action signal="changed">disable:'$1'_stored</action>
		</spinbutton>'
}

funcBtn() {
# $1 - Entry value; $@- all other arguments starting from the function followed
# by its arguments
	value=$1
	shift

	echo '<button>
			<input file stock="gtk-yes"></input>
			<action>'$EXECBASH' "'$@' $'$value' "</action>
			<action signal="button-press-event">enable:'$value'_stored</action>
		</button>'
}

funcStatusText() {
	echo '
		<text>
			<sensitive>false</sensitive>
			<variable>'$1'_stored</variable>
			<label>Stored</label>
		</text>'
}

funcWrite() {
# $1- Type; $2- Task name; $3- Field name; $4- Threshold value
	newline="[$(date +"%Y%m%d%H%M%S")] type|$1|task|$2|$3|$4"	
	echo $newline >> $FILEPATH

	echo "[cybathlon_gui] >> '$newline'"
}
#export -f funcWrite

if [ ! -d "$SAVEDIR" ]; then
	mkdir $SAVEDIR
	echo "[cybathlon_gui] Create new folder: $SAVEDIR"
fi

echo "[cybathlon_gui] Filepath: $FILEPATH"


MAIN_DIALOG='
<window title="'$WIN_TITLE'" resizable="false" width_request="'$WIN_W'" icon-name="gtk-about">
	<vbox>
		<hbox homogeneous="true">
			<pixmap>
			<input file>'"$LOGOPATH"'</input>
			<width>"'$IMG_W'"</width>
			</pixmap>
		</hbox>
		<hbox homogeneous="true">
			<vbox>
				<frame EMA-Integrator>
					
					<hbox>
						'`funcSpinEntry useralpha 0.0 1.0 0.01 0.97 alpha`'
						'`funcBtn useralpha funcWrite integrator ema alpha`'
						'`funcStatusText useralpha`'
					</hbox>
				</frame>

				<frame VEMA-Integrator>
						<hbox>
							'`funcSpinEntry userrho 0.0 1.0 0.01 0.97 rho`'
							'`funcBtn userrho funcWrite integrator vema rho`'
							'`funcStatusText userrho`'
						</hbox>
						<hbox>
							'`funcSpinEntry usergamma 0.0 1.0 0.01 0.97 gamma`'
							'`funcBtn usergamma funcWrite integrator vema gamma`'
							'`funcStatusText usergamma`'
						</hbox>
				</frame>
				
				<frame Dynamic-Integrator>
						<hbox>
							'`funcSpinEntry userphi 0.0 1.0 0.01 0.97 phi`'
							'`funcBtn userphi funcWrite integrator dynamic phi`'
							'`funcStatusText userphi`'
						</hbox>
				</frame>
			</vbox>
		</hbox>
		<hbox homogeneous="true">
			<button>
				<label>Close</label>
				<action>EXIT:OK</action>
			</button>
		</hbox>
	</vbox>
</window>
'

export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac



## Initialize SMR variables
#smr_label=mi
#smr_label_left=mi_left_hands
#smr_label_right=mi_right_hand
#smr_label_feet=mi_both_feet
#smr_label_hands=mi_both_hands
#smr_threshold_label=threshold
#smr_threshold_rangemin=0.50
#smr_threshold_rangemax=1.00
#smr_threshold_rangestep=0.01
#smr_threshold_initial=0.7
#
#export smr_label
#export smr_label_left
#export smr_label_right
#export smr_label_feet
#export smr_label_hands
#export smr_threshold_label
#export smr_threshold_rangemin
#export smr_threshold_rangemax
#export smr_threshold_rangestep
#export smr_threshold_initial
#
## Initialize EOG artifact variables
#artifact_label=artifact
#artifact_label_eog=artifact_eog
#eog_threshold_label=threshold
#eog_threshold_rangemin=0.0
#eog_threshold_rangemax=1000.0
#eog_threshold_rangestep=10.0
#eog_threshold_initial=300.0
#eog_timeout_label=timeout
#eog_timeout_rangemin=0.0
#eog_timeout_rangemax=5000.0
#eog_timeout_rangestep=500.0
#eog_timeout_initial=500.0
#
#export artifact_label
#export artifact_label_eog
#export eog_threshold_label
#export eog_threshold_rangemin
#export eog_threshold_rangemax
#export eog_threshold_rangestep
#export eog_threshold_initial
#export eog_timeout_label
#export eog_timeout_rangemin
#export eog_timeout_rangemax
#export eog_timeout_rangestep
#export eog_timeout_initial
#
####### FUNCTIONS
#
#funcHScale() {
## $1 - Variable name; $2 - Range Min; $3 - Range Max; $4 - Range Step; $5 -Default value; $6 - Title
#
#	echo '
#		<text space-expand="false" space-fill="false">
#			<label>'$6'</label>
#		</text>
#		<hscale space-expand="true" space-fill="true" range-min="'$2'" range-max="'$3'" range-step="'$4'"
#		tooltip-text="Threshold value" auto-refresh="true">
#			<default>'$5'</default>
#			<variable>'$1'</variable>
#			<action signal="value-changed">disable:'$1'_stored</action>
#		</hscale>'
#}
#
#funcBtn() {
## $1 - Entry value; $@- all other arguments starting from the function followed
## by its arguments
#	value=$1
#	shift
#
#	echo '<button>
#			<input file stock="gtk-yes"></input>
#			<action>'$EXECBASH' "'$@' $'$value' "</action>
#			<action signal="button-press-event">enable:'$value'_stored</action>
#		</button>'
#}
#
#funcSpinEntry() {
## $1 - Variable name; $2 - Range Min; $3 - Range Max; $4 - Range Step; $5 -Default value; $6 - Title
#	echo '
#		<text>
#			<label>'$6'</label>
#		</text>
#		<spinbutton digits="2" range-min="'$2'"
#		range-max="'$3'" range-step="'$4'"
#		range-value="'$5'"
#		tooltip-text="'$6' value">
#		<sensitive>true</sensitive>
#		<variable>'$1'</variable>
#		<action signal="changed">disable:'$1'_stored</action>
#		</spinbutton>'
#}
#
#funcStatusText() {
#	echo '
#		<text>
#			<sensitive>false</sensitive>
#			<variable>'$1'_stored</variable>
#			<label>Stored</label>
#		</text>'
#}
#
#funcWrite() {
## $1- Type; $2- Task name; $3- Field name; $4- Threshold value
#	newline="[$(date +"%Y%m%d%H%M%S")] type|$1|task|$2|$3|$4"	
#	echo $newline >> $FILEPATH
#
#	echo "[cybathlon_gui] >> '$newline'"
#}
#export -f funcWrite
#
#if [ ! -d "$SAVEDIR" ]; then
#	mkdir $SAVEDIR
#	echo "[cybathlon_gui] Create new folder: $SAVEDIR"
#fi
#
#echo "[cybathlon_gui] Filepath: $FILEPATH"
#
#
#MAIN_DIALOG='
#<window title="'$WIN_TITLE'" resizable="false" width_request="'$WIN_W'" icon-name="gtk-about">
#	<vbox>
#		<hbox homogeneous="true">
#			<pixmap>
#			<input file>'"$LOGOPATH"'</input>
#			<width>"'$IMG_W'"</width>
#			</pixmap>
#		</hbox>
#		<hbox homogeneous="true">
#			<vbox>
#				<frame SMR-BCI>
#					
#					<hbox homogeneous="true">
#						<text>
#							<label>Task Thresholds</label>
#						</text>
#					</hbox>
#
#					<hbox>
#						'`funcSpinEntry smr_threshold_value_rh $smr_threshold_rangemin $smr_threshold_rangemax $smr_threshold_rangestep $smr_threshold_initial RightHand`'
#						'`funcBtn smr_threshold_value_rh funcWrite $smr_label $smr_label_right $smr_threshold_label`'
#						'`funcStatusText smr_threshold_value_rh`'
#					</hbox>
#				
#					<hbox>
#						'`funcSpinEntry smr_threshold_value_lh $smr_threshold_rangemin $smr_threshold_rangemax $smr_threshold_rangestep $smr_threshold_initial LeftHand`'
#						'`funcBtn smr_threshold_value_lh funcWrite $smr_label $smr_label_left $smr_threshold_label`'
#						'`funcStatusText smr_threshold_value_lh`'
#					</hbox>
#					
#					<hbox>
#						'`funcSpinEntry smr_threshold_value_bh $smr_threshold_rangemin $smr_threshold_rangemax $smr_threshold_rangestep $smr_threshold_initial BothHands`'
#						'`funcBtn smr_threshold_value_bh funcWrite $smr_label $smr_label_hands $smr_threshold_label`'
#						'`funcStatusText smr_threshold_value_bh`'
#					</hbox>
#					
#					<hbox>
#						'`funcSpinEntry smr_threshold_value_bf $smr_threshold_rangemin $smr_threshold_rangemax $smr_threshold_rangestep $smr_threshold_initial BothFeet`'
#						'`funcBtn smr_threshold_value_bf funcWrite $smr_label $smr_label_feet $smr_threshold_label`'
#						'`funcStatusText smr_threshold_value_bf`'
#					</hbox>
#				</frame>
#
#				<frame EOG-Artifacts>
#					<hbox>
#						'`funcHScale eog_threshold_value $eog_threshold_rangemin $eog_threshold_rangemax $eog_threshold_rangestep $eog_threshold_initial Threshold`'
#						'`funcBtn eog_threshold_value funcWrite $artifact_label $artifact_label_eog $eog_threshold_label`'
#						'`funcStatusText eog_threshold_value`'
#					</hbox>
#					<hbox>
#						'`funcSpinEntry eog_timeout_value $eog_timeout_rangemin $eog_timeout_rangemax $eog_timeout_rangestep $eog_timeout_initial Timeout`'
#						'`funcBtn eog_timeout_value funcWrite $artifact_label $artifact_label_eog $eog_timeout_label`'
#						'`funcStatusText eog_timeout_value`'
#					</hbox>
#				</frame>
#			</vbox>
#		</hbox>
#		<hbox homogeneous="true">
#			<button>
#				<label>Close</label>
#				<action>EXIT:OK</action>
#			</button>
#		</hbox>
#	</vbox>
#</window>
#'
#
#export MAIN_DIALOG
#
#case $1 in
#	-d | --dump) echo "$MAIN_DIALOG" ;;
#	*) $GTKDIALOG --program=MAIN_DIALOG ;;
#esac
#
